export enum CategoryEnum {
  NONE, // AUCUNE
  PLUMBING, //PLOMBERIE
  MASONRY, // MACONNERIE
  CARPENTRY, // MENUISERIE
  ELECTRICITY,// ELECTRICITE
  FRAME, // CHARPENTE
  DRYWALL, // PLACO
  KITCHEN, // CUISINE
  COVERAGE, // COUVERTURE
  GARDEN, // JARDIN
  PAINT, //PEINTURE
  PLASTER // ENDUIT
}

